import { Event } from "./types";
import { normalizeDateToTaipeiISO, getTaipeiDateString } from "./normalize";

const DEMO_SOURCE = {
  name: "展示種子資料 (Demo Seed)",
  url: "https://events.example.tw/demo",
  fetchedAt: "2026-09-12T08:00:00+08:00",
  isDemo: true,
};

interface DemoEventDefinition {
  id: string;
  dayOffset: number; // relative to base date
  hour: number;
  minute: number;
  durationHours?: number;
  title: string;
  category: Event["category"];
  city: string;
  venue: string;
  priceText: string;
  description: string;
  url?: string;
}

const RAW_DEMO_DEFINITIONS: DemoEventDefinition[] = [
  {
    id: "demo-tpe-craft-2026",
    dayOffset: 0, // Today
    hour: 10,
    minute: 0,
    durationHours: 8,
    title: "2026 臺灣當代工藝與生活美學特展",
    category: "展覽",
    city: "臺北市",
    venue: "松山文創園區 2號倉庫",
    priceText: "免費入場",
    description: "匯集全臺40位工藝家，展現陶藝、竹編、漆藝與染織的現代生活器物風貌，現場定時舉辦工藝示範與修復講座。",
    url: "https://www.songshanculturalpark.tw",
  },
  {
    id: "demo-tpe-music-string",
    dayOffset: 1,
    hour: 19,
    minute: 30,
    durationHours: 2.5,
    title: "兩廳院秋季室內樂音樂會：島嶼弦之交響",
    category: "音樂",
    city: "臺北市",
    venue: "國家兩廳院 國家音樂廳",
    priceText: "NT$ 500 – 1,800",
    description: "由國家交響樂團首席弦樂重奏團演奏臺灣青年作曲家委託創作與經典德奧室內樂篇章。",
    url: "https://npac-ntch.org",
  },
  {
    id: "demo-tpe-talk-historic",
    dayOffset: 2,
    hour: 14,
    minute: 0,
    durationHours: 3,
    title: "走讀大稻埕：歷史街廓修復與老屋再生工作坊",
    category: "講座",
    city: "臺北市",
    venue: "大稻埕迪化街故事館",
    priceText: "NT$ 150 (含導覽手冊)",
    description: "資深文史修復建築師親自導覽，深入探討洋行建築立面與迪化街商圈永續保存案例。",
    url: "https://travel.taipei",
  },
  {
    id: "demo-ntp-outdoor-kayak",
    dayOffset: 3,
    hour: 15,
    minute: 30,
    durationHours: 3.5,
    title: "淡水河口夕陽獨木舟走讀與紅樹林生態巡禮",
    category: "戶外",
    city: "新北市",
    venue: "淡水文化園區 (原英商嘉士洋行倉庫岸邊)",
    priceText: "NT$ 850 (附專業教練與救生裝備)",
    description: "乘獨木舟迎著淡水金色落日，觀察水筆仔紅樹林生態與過境水鳥，適合初學者與家庭體驗。",
    url: "https://newtaipei.travel",
  },
  {
    id: "demo-ntp-family-ceramic",
    dayOffset: 4,
    hour: 10,
    minute: 30,
    durationHours: 3,
    title: "鶯歌陶瓷博物館：親子生活陶手捏手作研習營",
    category: "親子",
    city: "新北市",
    venue: "新北市立鶯歌陶瓷博物館 B1陶藝研習室",
    priceText: "材料費 NT$ 250",
    description: "專為學齡兒童與家長設計的陶藝啟蒙手作課，自製專屬的手捏陶碗與彩繪釉料燒製帶回家。",
    url: "https://www.ceramics.ntpc.gov.tw",
  },
  {
    id: "demo-kee-market-harbor",
    dayOffset: 5,
    hour: 13,
    minute: 0,
    durationHours: 6,
    title: "潮境海風港邊漁夫手作市集與海洋音樂匯",
    category: "市集",
    city: "基隆市",
    venue: "潮境公園 潮境海灣廣場",
    priceText: "免費入場",
    description: "邀集基隆在地漁青水產、石花凍手作飲品與海味文創選物，伴隨東北角海風與不插電吉他演奏。",
    url: "https://tour.klcg.gov.tw",
  },
  {
    id: "demo-tyn-exhibit-wood",
    dayOffset: 6,
    hour: 9,
    minute: 30,
    durationHours: 7.5,
    title: "大溪木藝生活特展：從神桌到現代綠色木器",
    category: "展覽",
    city: "桃園市",
    venue: "大溪木藝生態博物館 壹號館",
    priceText: "免費參觀",
    description: "紀錄大溪木器老街兩百年匠師工法，以互動木作模型引領觀眾認識榫接工藝的智慧。",
    url: "https://wem.tycg.gov.tw",
  },
  {
    id: "demo-hsc-talk-hack",
    dayOffset: 7,
    hour: 18,
    minute: 30,
    durationHours: 2.5,
    title: "風城開源沙龍：邊緣運算與在地科技應用小聚",
    category: "講座",
    city: "新竹市",
    venue: "新竹市東門市場 三樓青年基地",
    priceText: "免費 (需預先線上報名)",
    description: "竹科工程師與在地青年跨界交流，分享開源感測器監測新竹九降風與空氣品質之實戰專案。",
    url: "https://tourism.hccg.gov.tw",
  },
  {
    id: "demo-hsh-outdoor-hike",
    dayOffset: 8,
    hour: 8,
    minute: 0,
    durationHours: 7,
    title: "尖石巨木步道初秋健行：泰雅部落文化森林巡禮",
    category: "戶外",
    city: "新竹縣",
    venue: "尖石鄉司馬庫斯部落集會所",
    priceText: "NT$ 1,200 (含部落在地午餐與導覽)",
    description: "跟隨泰雅耆老的步伐走入千年紅檜森林，聆聽山林獵場傳奇與智慧生態共存觀念。",
    url: "https://travel.hsinchu.gov.tw",
  },
  {
    id: "demo-mal-show-hakka",
    dayOffset: 9,
    hour: 14,
    minute: 30,
    durationHours: 2,
    title: "山城韻律：客家山歌與現代跨界擊樂劇場",
    category: "表演",
    city: "苗栗縣",
    venue: "苗栗苗北藝文中心 演藝廳",
    priceText: "NT$ 300 – 800",
    description: "傳統山歌九腔十八調結合西方現代擊樂，開創屬於當代客庄的壯闊聲景新篇章。",
    url: "https://www.mbac.org.tw",
  },
  {
    id: "demo-txg-exhibit-art",
    dayOffset: 10,
    hour: 9,
    minute: 0,
    durationHours: 8,
    title: "島嶼光影足跡：臺灣近現代水彩與油畫特展",
    category: "展覽",
    city: "臺中市",
    venue: "國立臺灣美術館 102展覽室",
    priceText: "免費參觀",
    description: "梳理1930年代至當代臺灣前輩畫家筆下的鄉土山川、糖鐵市集與人文風光典藏作品。",
    url: "https://www.ntmofa.gov.tw",
  },
  {
    id: "demo-txg-market-shenji",
    dayOffset: 11,
    hour: 11,
    minute: 0,
    durationHours: 7,
    title: "審計新村秋日手作雜貨與獨立插畫市集",
    category: "市集",
    city: "臺中市",
    venue: "審計新村青創基地 綠蔭巷道",
    priceText: "免費入場",
    description: "匯集臺中在地陶藝家、金工飾品、手作甜點與原創插畫明信片，沉浸老宿舍懷舊氛圍。",
    url: "https://travel.taichung.gov.tw",
  },
  {
    id: "demo-cwh-fest-lukang",
    dayOffset: 12,
    hour: 10,
    minute: 0,
    durationHours: 8,
    title: "鹿港老街傳統工藝節暨錫藝木雕踩街盛會",
    category: "節慶",
    city: "彰化縣",
    venue: "鹿港公會堂前廣場及周邊紅磚巷道",
    priceText: "免費參觀",
    description: "邀請國寶級錫雕、燈籠彩繪大師現場獻藝，結合南北管樂團與民俗陣頭走讀鹿港風華。",
    url: "https://tourism.chcg.gov.tw",
  },
  {
    id: "demo-nto-sport-sunmoon",
    dayOffset: 13,
    hour: 6,
    minute: 0,
    durationHours: 4,
    title: "日月潭晨曦環湖長跑與自行車綠能自主挑戰賽",
    category: "運動",
    city: "南投縣",
    venue: "日月潭向山遊客中心 出發點",
    priceText: "NT$ 450 (含運動紀念排汗衫與完賽紀念木牌)",
    description: "清晨在湖光山色倒影中奔馳於全球知名環湖自行車道，享受無車干擾的清新微風。",
    url: "https://www.sunmoonlake.gov.tw",
  },
  {
    id: "demo-yun-show-puppet",
    dayOffset: 14,
    hour: 15,
    minute: 0,
    durationHours: 2,
    title: "偶戲春秋：臺灣掌中戲國寶折子戲經典重現",
    category: "表演",
    city: "雲林縣",
    venue: "雲林布袋戲館 後花園演武場",
    priceText: "免費入場",
    description: "黃家布袋戲傳人親自操偶演繹經典武打奇謀故事，現場開放小朋友親手操作金光戲偶。",
    url: "https://tour.yunlin.gov.tw",
  },
  {
    id: "demo-cyi-music-forest",
    dayOffset: 16,
    hour: 16,
    minute: 0,
    durationHours: 3,
    title: "阿里山林鐵聲景樂團：鐵道木材廠草地露天音樂會",
    category: "音樂",
    city: "嘉義市",
    venue: "嘉義製材所園區 大草坪",
    priceText: "免費自由入場",
    description: "在大跨距檜木廠房圍繞下，聆聽民謠管樂隊演奏阿里山古謠與鐵道工作者記憶樂章。",
    url: "https://travel.chiayi.gov.tw",
  },
  {
    id: "demo-tnn-fest-night",
    dayOffset: 18,
    hour: 18,
    minute: 0,
    durationHours: 4.5,
    title: "臺南古都百年巷弄秋夜提燈走讀與廟埕講古",
    category: "節慶",
    city: "臺南市",
    venue: "臺南孔廟文化園區 泮宮石坊前",
    priceText: "免費自由參加 (手提紙燈籠 NT$ 50)",
    description: "手提傳統竹製紙燈籠，穿梭神農街、赤嵌樓與孔廟暗香巷弄，聆聽府城四百年歷史軼聞。",
    url: "https://www.twtainan.net",
  },
  {
    id: "demo-tnn-other-food",
    dayOffset: 19,
    hour: 14,
    minute: 0,
    durationHours: 3,
    title: "府城食光溯源：常民飲食風味演變論壇",
    category: "其他",
    city: "臺南市",
    venue: "吳園藝文中心 展演廳",
    priceText: "NT$ 200 (附傳統碰餅茶點乙份)",
    description: "文史作家與老店傳人對談擔仔麵、虱目魚湯與節氣祭祀糕點背後的地理環境與人文哲學。",
    url: "https://culture.tainan.gov.tw",
  },
  {
    id: "demo-khh-show-dance",
    dayOffset: 20,
    hour: 19,
    minute: 30,
    durationHours: 2,
    title: "衛武營當代舞蹈旗艦劇作《風之軌跡》",
    category: "表演",
    city: "高雄市",
    venue: "衛武營國家藝術文化中心 歌劇院",
    priceText: "NT$ 600 – 2,200",
    description: "知名現代舞團集結24位國際舞者，運用榕樹樹冠流動意象詮釋南方海港生命的韌性與流轉。",
    url: "https://www.npac-weiwuying.org",
  },
  {
    id: "demo-khh-music-pier2",
    dayOffset: 21,
    hour: 20,
    minute: 0,
    durationHours: 3,
    title: "大港聲波：駁二秋日獨立搖滾樂團現場聚",
    category: "音樂",
    city: "高雄市",
    venue: "駁二藝術特區 Live Warehouse",
    priceText: "預售 NT$ 800 / 現場 NT$ 1,000",
    description: "高雄在地獨立樂團精選現場，在港邊倉庫震撼節奏中體驗港都熱血的青春原創力。",
    url: "https://pier2.org",
  },
  {
    id: "demo-pif-outdoor-wind",
    dayOffset: 22,
    hour: 9,
    minute: 0,
    durationHours: 5,
    title: "恆春半島落山風與社頂自然公園野地生機觀察",
    category: "戶外",
    city: "屏東縣",
    venue: "墾丁國家公園 社頂自然公園遊客中心",
    priceText: "NT$ 400 (含國家公園解說員導覽保險)",
    description: "迎著恆春特有的落山風，深入石灰岩珊瑚礁森林，觀察大冠鷲、梅花鹿與臺灣獼猴野外習性。",
    url: "https://www.i-pingtung.com",
  },
  {
    id: "demo-hua-family-kite",
    dayOffset: 24,
    hour: 14,
    minute: 0,
    durationHours: 4,
    title: "太平洋海風風箏彩繪創作與海濱家庭野餐日",
    category: "親子",
    city: "花蓮縣",
    venue: "花蓮太平洋公園 (南濱段草坪區)",
    priceText: "免費入場 (風箏材料包 NT$ 100)",
    description: "面向湛藍太平洋，放飛親手彩繪的手作風箏，並在草坪上享受海風與原住民手作小點心。",
    url: "https://tour-hualien.hl.gov.tw",
  },
  {
    id: "demo-ttt-music-tiehua",
    dayOffset: 25,
    hour: 19,
    minute: 0,
    durationHours: 2.5,
    title: "鐵花村原音傳唱：部落木吉他與星空草地分享會",
    category: "音樂",
    city: "臺東縣",
    venue: "鐵花村音樂聚落 草地舞台",
    priceText: "NT$ 250 (含指定在地飲品一杯)",
    description: "原住民創作歌手不插電真摯彈唱，結合彩繪熱氣球燈海微光，感受臺東夜晚最質樸的療癒時光。",
    url: "https://tour.taitung.gov.tw",
  },
  {
    id: "demo-pen-fest-sailing",
    dayOffset: 26,
    hour: 9,
    minute: 0,
    durationHours: 7,
    title: "菊島金秋風帆船邀請賽與沙灘落日海風野宴",
    category: "節慶",
    city: "澎湖縣",
    venue: "馬公市觀音亭親水遊憩區 沙灘段",
    priceText: "免費自由觀賽",
    description: "國內外各級風浪板好手齊聚澎湖灣競速追風，傍晚於西瀛虹橋下設有海島仙人掌手作風味市集。",
    url: "https://www.penghu-nsa.gov.tw",
  },
  {
    id: "demo-kin-exhibit-history",
    dayOffset: 27,
    hour: 10,
    minute: 0,
    durationHours: 6,
    title: "浯島歷史印記：金門戰役文獻與閩南紅磚聚落影像展",
    category: "展覽",
    city: "金門縣",
    venue: "金門和平紀念園區 展覽館",
    priceText: "免費參觀",
    description: "展出珍貴戰地老照片、僑鄉南洋書信與聚落傳統燕尾建築測繪圖，重現金門走過烽火的堅毅歲月。",
    url: "https://kinmen.travel",
  },
  {
    id: "demo-lie-outdoor-lighthouse",
    dayOffset: 28,
    hour: 19,
    minute: 0,
    durationHours: 3,
    title: "馬祖東犬燈塔夜間星空導覽與花崗岩地質步道夜行",
    category: "戶外",
    city: "連江縣",
    venue: "東莒島東犬燈塔園區",
    priceText: "免費預約導覽",
    description: "在百年英式白色燈塔守護下，仰望無光害銀河璀璨星空，並走訪馬祖海蝕地景夜間生態。",
    url: "https://www.matsu-nsa.gov.tw",
  },

  // Deliberately outside rolling 30-day window (to verify filtering tests)
  {
    id: "demo-past-summer-jazz",
    dayOffset: -20, // 20 days in past
    hour: 19,
    minute: 0,
    durationHours: 2,
    title: "[過期種子測試] 臺北夏季街頭爵士快閃音樂會",
    category: "音樂",
    city: "臺北市",
    venue: "大安森林公園 音樂台",
    priceText: "免費",
    description: "此活動為過去日期的測試資料，不應在當前30天有效視窗中顯示。",
  },
  {
    id: "demo-future-design-expo",
    dayOffset: 60, // 60 days in future
    hour: 10,
    minute: 0,
    durationHours: 8,
    title: "[遠期種子測試] 2027 臺灣未來設計概念前哨博覽會",
    category: "展覽",
    city: "高雄市",
    venue: "高雄流行音樂中心",
    priceText: "NT$ 200",
    description: "此活動為遠期未來的測試資料，不應在當前30天有效視窗中顯示。",
  },
];

/**
 * Generates deterministic demo events anchored around a reference date.
 * By default uses current date in Asia/Taipei so the rolling 30-day window
 * always contains the 26 in-window events across all Taiwan cities and categories.
 */
export function getDemoEvents(referenceDate: Date = new Date()): Event[] {
  // Convert referenceDate to Taipei midnight
  const utc = referenceDate.getTime() + referenceDate.getTimezoneOffset() * 60000;
  const taipeiNow = new Date(utc + 8 * 3600000);

  const baseYear = taipeiNow.getFullYear();
  const baseMonth = taipeiNow.getMonth();
  const baseDateNum = taipeiNow.getDate();

  return RAW_DEMO_DEFINITIONS.map((def) => {
    // Calculate start date in Taipei
    const evDate = new Date(Date.UTC(baseYear, baseMonth, baseDateNum + def.dayOffset, def.hour - 8, def.minute, 0));
    const startsAt = normalizeDateToTaipeiISO(evDate);

    let endsAt: string | undefined;
    if (def.durationHours) {
      const endEvDate = new Date(evDate.getTime() + def.durationHours * 3600000);
      endsAt = normalizeDateToTaipeiISO(endEvDate);
    }

    return {
      id: def.id,
      title: def.title,
      description: def.description,
      startsAt,
      endsAt,
      allDay: false,
      category: def.category,
      city: def.city,
      venue: def.venue,
      priceText: def.priceText,
      url: def.url,
      source: DEMO_SOURCE,
      updatedAt: "2026-09-12T08:00:00+08:00",
    };
  });
}
